### ISSUE TITLE
Throws fatal error on compiling IE filter with variable as argument

### ISSUE THREAD

**Issue by andrzejsitek** [darklow/ff-silex-less-provider#1]
When trying to compile a part of LESS code:
.opacity(@op:100) {
    filter:alpha(opacity=@op);
    -moz-opacity:@op/100;
    -khtml-opacity:@op/100;
    opacity:@op/100;
}

I get a fatal error:
Fatal error: Uncaught exception 'Exception' with message 'unknown value type: variable: failed at `filter:alpha(opacity=@op);` /Users/andrzej/Sites/microsite/web/css/main.less on line 50' in /Users/andrzej/Sites/microsite/vendor/leafo/lessphp/lessc.inc.php:3144 Stack trace: #0 /Users/andrzej/Sites/microsite/vendor/leafo/lessphp/lessc.inc.php(1786): lessc_parser->throwError('unknown value t...', 1234) #1 /Users/andrzej/Sites/microsite/vendor/leafo/lessphp/lessc.inc.php(785): lessc->throwError('unknown value t...') #2 /Users/andrzej/Sites/microsite/vendor/leafo/lessphp/lessc.inc.php(752): lessc->compileValue(Array) #3 /Users/andrzej/Sites/microsite/vendor/leafo/lessphp/lessc.inc.php(752): lessc->compileValue(Array) #4 /Users/andrzej/Sites/microsite/vendor/leafo/lessphp/lessc.inc.php(614): lessc->compileValue(Array) #5 /Users/andrzej/Sites/microsite/vendor/leafo/lessphp/lessc.inc.php(662): lessc->compileProp(Array, Object(stdClass), Object(stdClass)) #6 /Users/andrzej/Sites/microsite/vendor/leafo/lessphp/lessc.inc.php(277): in /Users/andrzej/Sites/microsite/vendor/leafo/lessphp/lessc.inc.php on line 3144

If I'll change filter value to:
filter:alpha(opacity=100);
It compiles.

**Comment by darklow** [comment]
As you can see by stack trace `lessphp/lessc.inc.php on line 3144` this is related to **lessphp** library and not the provider which is just a silex wrapper for lessphp library.

You should re-submit error report in lessphp package repository here: 
https://github.com/leafo/lessphp
